# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
users = User.create([{password: 123456, email_address: 'cscovdarth', first_name: 'Darth', planet: 'Tatooine', verified: false, bio: "The most pwoerful Sith Lord ever", avatar: "http://res.cloudinary.com/dvqilcc9p/image/upload/c_scale,r_30,w_128/v1523253129/darth_vader.webp", phone_number: "(123) 456-4567", superhost: false},
                     {password: 123456, email_address: 'cscovhan', first_name: 'Han', planet: 'Corellia', verified: false, bio: "Smuggler with a heart of gold", avatar: "http://res.cloudinary.com/dvqilcc9p/image/upload/c_scale,r_30,w_128/v1523253162/han.png", phone_number: "(123) 456-8901", superhost: false},
                     {password: 123456, email_address: 'cscovjyn', first_name: 'Jyn', planet: "La'Mu", verified: false, bio: "Just a rebel", avatar: "http://res.cloudinary.com/dvqilcc9p/image/upload/c_scale,r_30,w_128/v1523253133/jyn-erso_1.jpg", phone_number: "(123) 456-2345", superhost: false},
                     {password: 123456, email_address: 'cscovLando', first_name: 'Lando', planet: "Socorro", verified: false, bio: "I'm an entrepreneur. Let's make a deal", avatar: "http://res.cloudinary.com/dvqilcc9p/image/upload/c_scale,r_30,w_128/v1523253127/Lando_WoSW.jpg", phone_number: "(123) 456-7234", superhost: false},
                     {password: 123456, email_address: 'cscovobi', first_name: 'Obi-Wan', planet: 'Stewjon', verified: false, bio: "I will return more powerful than you can possibly imagine", avatar: "http://res.cloudinary.com/dvqilcc9p/image/upload/c_scale,r_30,w_128/v1523253161/obi_wan.jpg", phone_number: "(123) 456-8346", superhost: false},
                     {password: 123456, email_address: 'cscovpoe', first_name: 'Poe', planet: 'Yavin IV', verified: false, bio: "Rebel. The best pilot you've ever seen with the greatest leather jackets.", avatar: "http://res.cloudinary.com/dvqilcc9p/image/upload/c_scale,r_30,w_128/v1523253147/poe.jpg", phone_number: "(123) 456-2908", superhost: false},
                     {password: 123456, email_address: 'cscovluke', first_name: 'Luke', planet: 'Tatooine', verified: false, bio: "The folksiest farmboy you'll ever meet.", avatar: "http://res.cloudinary.com/dvqilcc9p/image/upload/c_scale,r_30,w_128/v1523253122/luke.jpg", phone_number: "(123) 456-5238", superhost: false},
                     {password: 123456, email_address: 'cscov', first_name: 'Leia', planet: 'Alderaan', verified: false, bio: "The only princess that matters.", avatar: "http://res.cloudinary.com/dvqilcc9p/image/upload/c_scale,r_30,w_128/v1523253137/leia.jpg", phone_number: "(123) 456-7216", superhost: false}])

spots = Spot.create([{host_id: 1, rental_type: "ENTIRE HOUSE", title: "Windswept Dunes", planet: "Tatooine", num_guests: 3, num_bedrooms: 2, num_baths: 1, daily_rate: 20, description: "I don't like sand. It's coarse and it's rough and it gets everywhere. That's  why I am renting out my childhood home. Hope you don't mind sand!", basic_amenity_category: true, wifi: false, indoor_fireplace: false, tv: true, iron: false,
  essentials: true, heating: false, air_conditioning: true, hot_water: true, facilities_amenity_category: true, parking: true,
  hot_tub: false, dining_amenity_category: true, kitchen: true, guest_access_amenity_category: true, lockbox: false, bed_bath_amenity_category: true, hangers: true, hair_dryer: false, shampoo: true, safety_amenity_category: true,
  fire_extinguisher: false, carbon_monoxide_detector: true, smoke_detector: true, first_aid_kit: true, not_included_amenity_category: true, washer: true, private_entrance: false, sleeping_arrangements: "1 queen bed and 1 twin bed", house_rules: "Just take off your shoes in the house and clean up after yourself", cancellation_policy: "Strict
Cancel up to 7 days before check in and get a 50% refund (minus service fees). Cancel within 7 days of your trip and the reservation is non-refundable. Service fees are refunded when cancellation happens before check in and within 48 hours of booking.", getting_around: "We usually ride banthas, but if you get lucky you could rent a podracer", address: "23 Dune Lane, Mos Eisley, Tatooine", directions: "Just head west from the spaceport", house_manual: "No parties. Quiet hours start at 10PM"},

{host_id: 1, rental_type: "ENTIRE HOUSE", title: "Windswept Dunes", planet: "Tatooine", num_guests: 3, num_bedrooms: 2, num_baths: 1, daily_rate: 20, description: "I don't like sand. It's coarse and it's rough and it gets everywhere. That's  why I am renting out my childhood home. Hope you don't mind sand!", basic_amenity_category: true, wifi: false, indoor_fireplace: false, tv: true, iron: false,
  essentials: true, heating: false, air_conditioning: true, hot_water: true, facilities_amenity_category: true, parking: true,
  hot_tub: false, dining_amenity_category: true, kitchen: true, guest_access_amenity_category: true, lockbox: false, bed_bath_amenity_category: true, hangers: true, hair_dryer: false, shampoo: true, safety_amenity_category: true,
  fire_extinguisher: false, carbon_monoxide_detector: true, smoke_detector: true, first_aid_kit: true, not_included_amenity_category: true, washer: true, private_entrance: false, sleeping_arrangements: "1 queen bed and 1 twin bed", house_rules: "Just take off your shoes in the house and clean up after yourself", cancellation_policy: "Strict
Cancel up to 7 days before check in and get a 50% refund (minus service fees). Cancel within 7 days of your trip and the reservation is non-refundable. Service fees are refunded when cancellation happens before check in and within 48 hours of booking.", getting_around: "We usually ride banthas, but if you get lucky you could rent a podracer", address: "23 Dune Lane, Mos Eisley, Tatooine", directions: "Just head west from the spaceport", house_manual: "No parties. Quiet hours start at 10PM"},

{host_id: 1, rental_type: "ENTIRE HOUSE", title: "Windswept Dunes", planet: "Tatooine", num_guests: 3, num_bedrooms: 2, num_baths: 1, daily_rate: 20, description: "I don't like sand. It's coarse and it's rough and it gets everywhere. That's  why I am renting out my childhood home. Hope you don't mind sand!", basic_amenity_category: true, wifi: false, indoor_fireplace: false, tv: true, iron: false,
  essentials: true, heating: false, air_conditioning: true, hot_water: true, facilities_amenity_category: true, parking: true,
  hot_tub: false, dining_amenity_category: true, kitchen: true, guest_access_amenity_category: true, lockbox: false, bed_bath_amenity_category: true, hangers: true, hair_dryer: false, shampoo: true, safety_amenity_category: true,
  fire_extinguisher: false, carbon_monoxide_detector: true, smoke_detector: true, first_aid_kit: true, not_included_amenity_category: true, washer: true, private_entrance: false, sleeping_arrangements: "1 queen bed and 1 twin bed", house_rules: "Just take off your shoes in the house and clean up after yourself", cancellation_policy: "Strict
Cancel up to 7 days before check in and get a 50% refund (minus service fees). Cancel within 7 days of your trip and the reservation is non-refundable. Service fees are refunded when cancellation happens before check in and within 48 hours of booking.", getting_around: "We usually ride banthas, but if you get lucky you could rent a podracer", address: "23 Dune Lane, Mos Eisley, Tatooine", directions: "Just head west from the spaceport", house_manual: "No parties. Quiet hours start at 10PM"},

{host_id: 1, rental_type: "ENTIRE HOUSE", title: "Windswept Dunes", planet: "Tatooine", num_guests: 3, num_bedrooms: 2, num_baths: 1, daily_rate: 20, description: "I don't like sand. It's coarse and it's rough and it gets everywhere. That's  why I am renting out my childhood home. Hope you don't mind sand!", basic_amenity_category: true, wifi: false, indoor_fireplace: false, tv: true, iron: false,
  essentials: true, heating: false, air_conditioning: true, hot_water: true, facilities_amenity_category: true, parking: true,
  hot_tub: false, dining_amenity_category: true, kitchen: true, guest_access_amenity_category: true, lockbox: false, bed_bath_amenity_category: true, hangers: true, hair_dryer: false, shampoo: true, safety_amenity_category: true,
  fire_extinguisher: false, carbon_monoxide_detector: true, smoke_detector: true, first_aid_kit: true, not_included_amenity_category: true, washer: true, private_entrance: false, sleeping_arrangements: "1 queen bed and 1 twin bed", house_rules: "Just take off your shoes in the house and clean up after yourself", cancellation_policy: "Strict
Cancel up to 7 days before check in and get a 50% refund (minus service fees). Cancel within 7 days of your trip and the reservation is non-refundable. Service fees are refunded when cancellation happens before check in and within 48 hours of booking.", getting_around: "We usually ride banthas, but if you get lucky you could rent a podracer", address: "23 Dune Lane, Mos Eisley, Tatooine", directions: "Just head west from the spaceport", house_manual: "No parties. Quiet hours start at 10PM"},

{host_id: 1, rental_type: "ENTIRE HOUSE", title: "Windswept Dunes", planet: "Tatooine", num_guests: 3, num_bedrooms: 2, num_baths: 1, daily_rate: 20, description: "I don't like sand. It's coarse and it's rough and it gets everywhere. That's  why I am renting out my childhood home. Hope you don't mind sand!", basic_amenity_category: true, wifi: false, indoor_fireplace: false, tv: true, iron: false,
  essentials: true, heating: false, air_conditioning: true, hot_water: true, facilities_amenity_category: true, parking: true,
  hot_tub: false, dining_amenity_category: true, kitchen: true, guest_access_amenity_category: true, lockbox: false, bed_bath_amenity_category: true, hangers: true, hair_dryer: false, shampoo: true, safety_amenity_category: true,
  fire_extinguisher: false, carbon_monoxide_detector: true, smoke_detector: true, first_aid_kit: true, not_included_amenity_category: true, washer: true, private_entrance: false, sleeping_arrangements: "1 queen bed and 1 twin bed", house_rules: "Just take off your shoes in the house and clean up after yourself", cancellation_policy: "Strict
Cancel up to 7 days before check in and get a 50% refund (minus service fees). Cancel within 7 days of your trip and the reservation is non-refundable. Service fees are refunded when cancellation happens before check in and within 48 hours of booking.", getting_around: "We usually ride banthas, but if you get lucky you could rent a podracer", address: "23 Dune Lane, Mos Eisley, Tatooine", directions: "Just head west from the spaceport", house_manual: "No parties. Quiet hours start at 10PM"},

{host_id: 1, rental_type: "ENTIRE HOUSE", title: "Windswept Dunes", planet: "Tatooine", num_guests: 3, num_bedrooms: 2, num_baths: 1, daily_rate: 20, description: "I don't like sand. It's coarse and it's rough and it gets everywhere. That's  why I am renting out my childhood home. Hope you don't mind sand!", basic_amenity_category: true, wifi: false, indoor_fireplace: false, tv: true, iron: false,
  essentials: true, heating: false, air_conditioning: true, hot_water: true, facilities_amenity_category: true, parking: true,
  hot_tub: false, dining_amenity_category: true, kitchen: true, guest_access_amenity_category: true, lockbox: false, bed_bath_amenity_category: true, hangers: true, hair_dryer: false, shampoo: true, safety_amenity_category: true,
  fire_extinguisher: false, carbon_monoxide_detector: true, smoke_detector: true, first_aid_kit: true, not_included_amenity_category: true, washer: true, private_entrance: false, sleeping_arrangements: "1 queen bed and 1 twin bed", house_rules: "Just take off your shoes in the house and clean up after yourself", cancellation_policy: "Strict
Cancel up to 7 days before check in and get a 50% refund (minus service fees). Cancel within 7 days of your trip and the reservation is non-refundable. Service fees are refunded when cancellation happens before check in and within 48 hours of booking.", getting_around: "We usually ride banthas, but if you get lucky you could rent a podracer", address: "23 Dune Lane, Mos Eisley, Tatooine", directions: "Just head west from the spaceport", house_manual: "No parties. Quiet hours start at 10PM"},

{host_id: 1, rental_type: "ENTIRE HOUSE", title: "Windswept Dunes", planet: "Tatooine", num_guests: 3, num_bedrooms: 2, num_baths: 1, daily_rate: 20, description: "I don't like sand. It's coarse and it's rough and it gets everywhere. That's  why I am renting out my childhood home. Hope you don't mind sand!", basic_amenity_category: true, wifi: false, indoor_fireplace: false, tv: true, iron: false,
  essentials: true, heating: false, air_conditioning: true, hot_water: true, facilities_amenity_category: true, parking: true,
  hot_tub: false, dining_amenity_category: true, kitchen: true, guest_access_amenity_category: true, lockbox: false, bed_bath_amenity_category: true, hangers: true, hair_dryer: false, shampoo: true, safety_amenity_category: true,
  fire_extinguisher: false, carbon_monoxide_detector: true, smoke_detector: true, first_aid_kit: true, not_included_amenity_category: true, washer: true, private_entrance: false, sleeping_arrangements: "1 queen bed and 1 twin bed", house_rules: "Just take off your shoes in the house and clean up after yourself", cancellation_policy: "Strict
Cancel up to 7 days before check in and get a 50% refund (minus service fees). Cancel within 7 days of your trip and the reservation is non-refundable. Service fees are refunded when cancellation happens before check in and within 48 hours of booking.", getting_around: "We usually ride banthas, but if you get lucky you could rent a podracer", address: "23 Dune Lane, Mos Eisley, Tatooine", directions: "Just head west from the spaceport", house_manual: "No parties. Quiet hours start at 10PM"},

{host_id: 1, rental_type: "ENTIRE HOUSE", title: "Windswept Dunes", planet: "Tatooine", num_guests: 3, num_bedrooms: 2, num_baths: 1, daily_rate: 20, description: "I don't like sand. It's coarse and it's rough and it gets everywhere. That's  why I am renting out my childhood home. Hope you don't mind sand!", basic_amenity_category: true, wifi: false, indoor_fireplace: false, tv: true, iron: false,
  essentials: true, heating: false, air_conditioning: true, hot_water: true, facilities_amenity_category: true, parking: true,
  hot_tub: false, dining_amenity_category: true, kitchen: true, guest_access_amenity_category: true, lockbox: false, bed_bath_amenity_category: true, hangers: true, hair_dryer: false, shampoo: true, safety_amenity_category: true,
  fire_extinguisher: false, carbon_monoxide_detector: true, smoke_detector: true, first_aid_kit: true, not_included_amenity_category: true, washer: true, private_entrance: false, sleeping_arrangements: "1 queen bed and 1 twin bed", house_rules: "Just take off your shoes in the house and clean up after yourself", cancellation_policy: "Strict
Cancel up to 7 days before check in and get a 50% refund (minus service fees). Cancel within 7 days of your trip and the reservation is non-refundable. Service fees are refunded when cancellation happens before check in and within 48 hours of booking.", getting_around: "We usually ride banthas, but if you get lucky you could rent a podracer", address: "23 Dune Lane, Mos Eisley, Tatooine", directions: "Just head west from the spaceport", house_manual: "No parties. Quiet hours start at 10PM"}])
